### PR TITLE
Implement kmeans with kmeans++

### PR DESCRIPTION
**Pull request by vberezhnev**

### CODE REVIEW

**Review by ichorid — CHANGES_REQUESTED** [review]
Please add tests and remove CI/CD stuff (that is subject to a separate PR). Also, move the k-means algorithm into a separate file.

**Comment by vberezhnev** [comment]
@automainint What do you think about moving files like `clustering.rs`, `log.rs`, and `astar.rs` into a separate folder specifically for libraries?

**Comment by automainint** [comment]
> @automainint What do you think about moving files like `clustering.rs`, `log.rs`, and `astar.rs` into a separate folder specifically for libraries?

I usually avoid adding abstractions without a specific reason. E.g. `protocol.rs` is a separate file because it's used by the psql-connector, while some other parts of the service are not. `protocol.rs` depends on `log.rs`, but not on `astar.rs`, so `log.rs` and `astar.rs` have distinct status, and it's not obvious that they have to be grouped together.

**Review by automainint — CHANGES_REQUESTED** [review]
Each function that returns a score should also return the cluster value for that score. So we have to change function signatures, and it's probably better to apply (or read cached) clusters in functions `fetch_score` and `fetch_all_scores`.

Currently `read_mutual_scores` doesn't apply clustering correctly. All scores **from** a user node should be clustered, not all scores **to** a user node.

I will change function signatures and write tests in the new branch [feature/score_clustering](https://github.com/Intersubjective/meritrank-rust/tree/feature/score_clustering).

Also we will have to implement caching of clusters as "group bounds", as mentioned in https://github.com/Intersubjective/meritrank-rust/issues/10#issuecomment-2455294066 by @ichorid.

**Pull request closed without merging**
